class Constant(object):
    SLASH_STAR = '/*'
    MULTIPLE_COMENT_END_SYMBOL = '*/'
    STAR = '*'
    DOUBLE_SLASH = '//'
    LEFT_BRACE = '{'
    RIGHT_BRACE = '}'
    LEFT_SQUARE_BRACKET = '['
    RIGHT_SQUARE_BRACKET = ']'
    EQUAL_SIGN = '='
    SEMICOLON = ';'
    ANGLE_BRACKET_LEFT = '<'
    RIGHT_ANGLE_BRACKET = '>'
